% An article class for a classically formatted humanities paper
%   humapap-dev.cls
% Created by Maarten Steenhagen 
% Department of Philosophy
% University College London
% m.steenhagen.09@ucl.ac.uk
% Drawing on, amongst others, Mark Sprevak's mds-article class

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{humapap}[2015/05/16 Hello, this is the HumaPap article class. Currently this class is under development.]
\LoadClass[a4paper,12pt, twoside]{article}
